### ISSUE TITLE
Mint 18 bash fails at running OpenSSL tests

### ISSUE THREAD

**Issue by ricardobranco777** [linuxmint/bash#1]
See https://github.com/openssl/openssl/issues/1623

To reproduce:

```
wget -P /tmp https://www.openssl.org/source/openssl-1.0.2j.tar.gz
cd /tmp
tar xf openssl-1.0.2j.tar.gz
cd openssl-1.1.0b
./config --prefix=/usr/local/ssl enable-ssl-trace ; make ; make test
```

I had to "downgrade" to Ubuntu 16 bash to get them ok.

`sudo apt-get install bash=4.3-14ubuntu1.1`

**Comment by clefebvre** [comment]
Thanks. Fixed by https://github.com/linuxmint/bash/commit/1979004ccf63a0d7f1e83ba771bfb6dd264878cb

This is targeted at Serena and can be backported to Sarah post-BETA.
